title: test1
description: test
steps:
  - course: test1
    description: test1
  - link: 'javascript:alert(1);'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
